// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

dotenv.config({ 
  path: path.resolve(import.meta.dirname, "../../.env")
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection used for runtime queries. Migrate uses directUrl
    // when set so it can run statements PgBouncer's transaction pool
    // rejects (CREATE INDEX CONCURRENTLY, advisory locks, etc).
    url: env("DATABASE_URL"),
    directUrl: process.env.DIRECT_DATABASE_URL,
  },
});
